version: '3.8'
services:
  flask:
    build: .
    volumes:
      - .:/app
      - ./static:/app/static
      - ./templates:/app/templates
    ports:
      - "5000:5000"
    depends_on:
      - crime_behaviour
      - resource_area
      # - public_area

  crime_behaviour:
    build: ./models/crime_behaviour
    volumes:
      - ./models/crime_behaviour:/app/weights
    ports:
      - "5001:5000"
  
  resource_area:
    build: ./models/resource_area
    volumes:
      - ./models/resource_area/weights:/app/weights
    ports:
      - "5002:5000"
  
  # public_area:
  #   build: ./models/public_area
  #   volumes:
  #     - ./models/public_area/weights:/app/weights
  #   ports:
  #     - "5003:5000"
